//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngDotNet.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastLogedIn { get; set; }
    }
}
